== SpringBootMVCHello

Simple example of Spring-boot with Spring MVC based on the following guides :

* https://spring.io/guides/gs/spring-boot/
* https://spring.io/guides/gs/accessing-data-jpa/
* https://spring.io/guides/gs/accessing-data-mysql/

=== How to run it

*Requirements :* Docker and docker-compose installed.

After cloning the project :

[source,bash]
----
$ cd SpringBootMVCHello
$ docker-compose up -d
$ docker-inspect springbootmvchello_app_1 | grep Address
            "LinkLocalIPv6Address": "",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "GlobalIPv6Address": "",
            "IPAddress": "",
            "MacAddress": "",
                    "IPAddress": "172.22.0.3",
                    "GlobalIPv6Address": "",
                    "MacAddress": "02:42:ac:16:00:03",
----

Look for the line matching IPAddress, in this example :

    "IPAddress": "172.22.0.3"

In your web browser, go to http://172.22.0.3:8080

If it works, you can go to http://172.22.0.3:8080/customers to verify that the application is connecting to the MariaDB database container.

When using it for real, don't forget to modify the default database user and password in :

* db/mysql.sql for the MariaDB container
* src/main/resources/application.properties for the application container.

You can watch the logs with the following command :

[source,bash]
----
$ docker-compose logs -f
----

After the first launch, you can stop the containers like that :

[source,bash]
----
$ docker-compose stop
----

The next start is done with :

[source,bash]
----
$ docker-compose start
----

=== To stop and destroy the containers

[source,bash]
----
$ docker-compose down
----

This last command will erase all content and databases from your hard drive.


